# RUN: exec $cmd --trace-exit $self
# STATUS: 1

function throw(e: Throwable?) {
    if let a = $e as? ShellExit {
        echo rethrow ${$a.name()}
        throw $a
    } elif let a = $e as? AssertionFailed {
                echo rethrow ${$a.name()}
        throw $a
    } else {
        echo nothrow
    }
}

defer { ## check suppressed error
    $THROWN!.suppressed().clear()  # not affect underlying data
    assert $THROWN!.suppressed().size() == 2
    assert $THROWN!.suppressed()[0].suppressed().empty()
    assert $THROWN!.suppressed()[1].suppressed().empty()
}

defer {
    defer {
        $throw($THROWN)
    }
    command 'exit'
}

defer {
    defer {
        $throw($THROWN)
    }

    assert $THROWN is ShellExit
}

23/0

# CHECK: rethrow AssertionFailed
# CHECK: rethrow ShellExit

# CHECKERR: [runtime error]
# CHECKERR: ArithmeticError: zero division
# CHECKERR_RE:     from .+/test/exec/cases/output/thrown3\.ds:38 '<toplevel>\(\)'
# CHECKERR: [note] the following exceptions are suppressed
# CHECKERR: AssertionFailed: `$THROWN is ShellExit'
# CHECKERR: binary expression `<EXPR> is <TYPE>' is false
# CHECKERR:   <EXPR>: ArithmeticError
# CHECKERR:   <TYPE>: ShellExit
# CHECKERR_RE:     from .+/test/exec/cases/output/thrown3\.ds:35 '<toplevel>\(\)'
# CHECKERR: ShellExit: terminated by exit 0
# CHECKERR_RE:     from .+/test/exec/cases/output/thrown3\.ds:27 '<toplevel>\(\)'
