# test try-catch stack guard

# no except
assert "45" == try {
    "45"
} catch e {
    $e.message()
}

# catch
assert 34 == try {
    34 / 0
} catch e {
    $e
    65
    try {
        34 + throw $e
    } catch ex {
        34
    }
}

# nested try-catch
assert "aaa" == try {
    34
    try {
        "aaaaa"[34]
    } catch e : ArithmeticError {
        "bbb"
    }
} catch e : OutOfRangeError {
    "aaa"
}

assert 12 == try {
    34
    try {
        12
    } catch e : ArithmeticError {
        "bbb".size()
    }
} catch e : OutOfRangeError {
    "aaa".size()
}